// jazz_data.js — Song library and practice priority order
// Edit this file to add, remove, or re-prioritize songs.
// Format: [title, initialLevel (0–3), style]

const ALL_SONGS = [
  ["Stella by Starlight",2,""],["Spring Is Here",0,""],["Rhythm-a-ning",0,""],
  ["Limehouse Blues",0,""],["Nature Boy",0,""],["I Should Care",0,""],
  ["Good Morning Heartache",0,""],["Body and Soul",0,""],["I've Found a New Baby",0,""],
  ["Willow Weep for Me",0,""],["Falling in Love with Love",0,""],["Lover Man",0,""],
  ["Out of Nowhere",0,""],["On the Sunny Side of the Street",2,"Trad"],["Con Alma",0,""],
  ["Stolen Moments",0,""],["On a Clear Day",0,""],["Perdido",0,""],
  ["Night Train",0,""],["Take the A Train",2,""],["Steeplechase",2,"Bop"],
  ["Evidence",0,""],["Well You Needn't",1,"Bop"],["Giant Steps",0,""],
  ["How Long Has This Been Going On?",0,""],["Blue in Green",2,"Modal"],["St. Thomas",1,""],
  ["Embraceable You",0,""],["The Girl from Ipanema",0,"Bossa"],["I Hear a Rhapsody",0,""],
  ["But Not for Me",2,""],["After You've Gone",2,"Trad"],["It Don't Mean a Thing",0,"Trad"],
  ["When the Saints Go Marching In",0,""],["Night in Tunisia",0,"Bop"],["Bags' Groove",0,"Blues"],
  ["Easy Living",0,""],["My Old Flame",0,""],["But Beautiful",0,""],
  ["Watermelon Man",0,""],["Gee Baby Ain't I Good to You",0,""],["Don't Blame Me",0,""],
  ["I Fall in Love Too Easily",0,""],["Ornithology",1,"Bop"],["You Stepped Out of a Dream",0,""],
  ["How Deep Is the Ocean?",0,""],["Mean to Me",0,""],["Fascinating Rhythm",0,""],
  ["Poinciana",0,""],["Autumn in New York",0,""],["Do You Know What It Means",2,"Trad"],
  ["All of Me",3,""],["Memories of You",0,""],["I Let a Song Go Out of My Heart",0,""],
  ["C Jam Blues",3,"Blues"],["Speak Low",0,""],["Stompin' at the Savoy",0,"Trad"],
  ["It Had to Be You",0,""],["Bye Bye Blackbird",0,""],["In a Sentimental Mood",0,""],
  ["Satin Doll",1,"Trad"],["Song for My Father",0,""],["The Nearness of You",2,""],
  ["Some of These Days",0,""],["Peace",0,""],["I Mean You",0,""],
  ["Maiden Voyage",0,"Modal"],["Smile",0,""],["How Insensitive",0,"Bossa"],
  ["A Child Is Born",0,""],["Like Someone in Love",0,""],["Night and Day",3,""],
  ["I Cover the Waterfront",0,""],["Blue Skies",2,"Trad"],["Ghost of a Chance",0,""],
  ["Anthropology",1,"Bop"],["East of the Sun",0,""],["The Jitterbug Waltz",0,""],
  ["Lover Come Back to Me",0,""],["My One and Only Love",0,""],["Dinah",0,"Trad"],
  ["Eternal Triangle",0,"Bop"],["Don't Get Around Much Anymore",0,""],["Misterioso",0,""],
  ["Old Folks",0,""],["Alone Together",2,""],["Impressions",0,"Modal"],
  ["Solitude",0,""],["Round Midnight",0,""],["Mood Indigo",0,""],
  ["Fly Me to the Moon",1,""],["Now's the Time",0,"Bop"],["Exactly Like You",0,""],
  ["Honeysuckle Rose",0,"Trad"],["Blue Moon",0,""],["Blues for Alice",1,"Bop"],
  ["Mack the Knife",0,"Trad"],["Invitation",0,""],["Cantaloupe Island",2,""],
  ["Come Sunday",0,""],["In a Mellow Tone",0,""],["Ain't Misbehavin'",0,"Trad"],
  ["More Than You Know",0,""],["These Foolish Things",0,""],["Donna Lee",3,"Bop"],
  ["Alfie",0,""],["All Blues",3,""],["Moanin'",0,""],
  ["Star Dust",0,""],["Nice Work If You Can Get It",0,""],["Spring Can Really Hang You Up the Most",0,""],
  ["Wave",0,"Bossa"],["Everything Happens to Me",0,""],["I Got It Bad",0,""],
  ["Oleo",2,"Bop"],["Beale Street Blues",0,""],["Milestones",0,""],
  ["It's Easy to Remember",0,""],["Joy Spring",0,"Bop"],["Liza",0,""],
  ["A Foggy Day",0,""],["Yardbird Suite",2,"Bop"],["Groovin' High",0,"Bop"],
  ["Sophisticated Lady",0,""],["I Didn't Know What Time It Was",0,""],["Oh Lady Be Good",0,""],
  ["Lester Leaps In",2,"Bop"],["Things Ain't What They Used to Be",0,""],["Georgia on My Mind",0,""],
  ["Tin Roof Blues",0,""],["I Remember Clifford",0,""],["Whisper Not",0,""],
  ["Bemsha Swing",0,""],["Ruby My Dear",0,""],["How High the Moon",0,""],
  ["My Romance",3,""],["Tenderly",0,""],["Dolphin Dance",0,""],
  ["Airegin",0,""],["You Go to My Head",0,""],["St. James Infirmary Blues",2,"Trad"],
  ["It Never Entered My Mind",0,""],["Pennies from Heaven",0,"Trad"],["Tiger Rag",0,""],
  ["Misty",1,""],["Meditation",0,"Bossa"],["Love for Sale",0,""],
  ["I Thought about You",0,""],["Sweet Georgia Brown",0,""],["Darn That Dream",0,""],
  ["In Your Own Sweet Way",0,""],["Goodbye Pork Pie Hat",0,""],["Lush Life",0,""],
  ["Chelsea Bridge",0,""],["The Very Thought of You",0,""],["Love Is Here to Stay",0,""],
  ["My Funny Valentine",1,"Trad"],["The Lady Is a Tramp",0,""],["Confirmation",0,"Bop"],
  ["Lotus Blossom",0,""],["The Peacocks",0,""],["Blue Bossa",3,"Bossa"],
  ["All the Things You Are",2,""],["Django",0,"Trad"],["Secret Love",0,""],
  ["My Heart Stood Still",0,""],["Birdland",0,""],["Waltz for Debby",0,""],
  ["My Foolish Heart",0,""],["Star Eyes",0,""],["Someone to Watch over Me",0,""],
  ["Days of Wine and Roses",0,""],["One O'Clock Jump",0,"Blues"],["Soul Eyes",1,""],
  ["Over the Rainbow",1,""],["Moment's Notice",0,""],["Straight No Chaser",3,"Blues"],
  ["Tea for Two",0,""],["Along Came Betty",0,""],["Blue Monk",3,"Blues"],
  ["Nardis",3,""],["St. Louis Blues",3,"Blues"],["Here's That Rainy Day",0,""],
  ["April in Paris",0,""],["So What",3,"Modal"],["Easy to Love",0,""],
  ["Just One of Those Things",0,""],["There Is No Greater Love",3,""],["One Note Samba",0,""],
  ["King Porter Stomp",0,""],["Hot House",0,"Bop"],["Angel Eyes",0,""],
  ["Bluesette",0,""],["I Got Rhythm",1,"Trad"],["I Can't Give You Anything but Love",0,""],
  ["Blues in the Night",0,""],["Caravan",0,"Bop"],["What's New?",0,""],
  ["I Love You",0,""],["Do Nothin' Till You Hear from Me",0,""],["Lover",0,""],
  ["All of You",2,""],["Nuages",0,""],["Almost Like Being in Love",0,""],
  ["You Don't Know What Love Is",0,""],["Footprints",1,"Modal"],["Lullaby of Birdland",0,""],
  ["I Can't Get Started",0,""],["Someday My Prince Will Come",2,""],["S Wonderful",0,""],
  ["Softly as in a Morning Sunrise",3,""],["I'll Remember April",2,""],["I'm in the Mood for Love",0,""],
  ["Lady Bird",2,""],["Smoke Gets in Your Eyes",0,""],["Ev'ry Time We Say Goodbye",0,""],
  ["If You Could See Me Now",0,""],["Corcovado",0,""],["Stormy Weather",0,""],
  ["Polka Dots and Moonbeams",0,""],["Have You Met Miss Jones?",0,""],["Cherokee",0,"Bop"],
  ["Once I Loved",0,""],["Emily",0,""],["Solar",0,""],
  ["Manhã de Carnaval",0,""],["The Shadow of Your Smile",0,""],["God Bless the Child",2,""],
  ["Gone with the Wind",0,""],["If I Should Lose You",0,""],["On Green Dolphin Street",2,""],
  ["Desafinado",0,""],["Prelude to a Kiss",0,""],["There Will Never Be Another You",1,""],
  ["I Want to Be Happy",0,""],["The Way You Look Tonight",0,""],["It Could Happen to You",0,""],
  ["The Man I Love",0,""],["Take Five",2,""],["A Sleepin Bee",2,""],
  ["Yesterdays",0,""],["They Can't Take That Away from Me",0,""],["What Is This Thing Called Love?",0,""],
  ["Struttin' with Some Barbecue",0,""],["Autumn Leaves",3,""],["Muskrat Ramble",0,""],
  ["Naima",0,""],["Royal Garden Blues",0,""],["Lament",0,""],
  ["Time after Time",0,""],["Basin Street Blues",2,"Blues"],["Just You Just Me",0,""],
  ["Lonely Woman",0,""],["Who Can I Turn To?",0,""],["It Might as Well Be Spring",0,""],
  ["Moose the Mooche",0,"Bop"],["Skylark",0,""],["Just Friends",3,""],
  ["Summertime",1,"Trad"],["Laura",0,""],["The Song Is You",0,""],
  ["I Surrender Dear",0,""],["My Favorite Things",2,""],["Billie's Bounce",2,"Bop"],
  ["Scrapple from the Apple",1,"Bop"],["Epistrophy",0,""],["I Only Have Eyes for You",0,""],
  ["Cotton Tail",0,""],["Moonlight in Vermont",0,""],["You'd Be So Nice to Come Home To",0,""],
  ["Come Rain or Come Shine",0,""],["Indiana",0,""]
];

// Songs ordered by jam-session priority — learned first.
// Level 1 songs appear at the top (fastest ROI), then high-frequency level 0 standards.
const PRIORITY_ORDER = [
  "Anthropology","Blues for Alice","Fly Me to the Moon","Footprints","I Got Rhythm",
  "Misty","My Funny Valentine","Ornithology","Over the Rainbow","Satin Doll",
  "Scrapple from the Apple","Soul Eyes","St. Thomas","Summertime",
  "There Will Never Be Another You","Well You Needn't","Autumn in New York",
  "Body and Soul","Come Rain or Come Shine","Days of Wine and Roses",
  "Have You Met Miss Jones?","How High the Moon","In a Sentimental Mood",
  "It Could Happen to You","Just One of Those Things","Laura","Maiden Voyage",
  "Night in Tunisia","Now's the Time","Round Midnight","Solar",
  "The Girl from Ipanema","Waltz for Debby","Watermelon Man",
  "What Is This Thing Called Love?","Yesterdays","Cherokee","Confirmation",
  "Dolphin Dance","Embraceable You","Giant Steps","Joy Spring","Lush Life",
  "Moment's Notice","Stolen Moments","Bye Bye Blackbird","Caravan",
  "Georgia on My Mind","Here's That Rainy Day","How Deep Is the Ocean?",
  "I Can't Get Started","Like Someone in Love","Lover Man","Nature Boy",
  "Naima","Speak Low","Angel Eyes","But Beautiful","Ghost of a Chance",
  "I Only Have Eyes for You","In Your Own Sweet Way","Moonlight in Vermont",
  "I Remember Clifford","Skylark","Emily","Everything Happens to Me",
  "Darn That Dream","East of the Sun","Airegin","Bemsha Swing","Bluesette",
  "Chelsea Bridge","Con Alma","Cotton Tail","Desafinado","Epistrophy",
  "Eternal Triangle","Evidence","Goodbye Pork Pie Hat","Groovin' High",
  "Hot House","How Insensitive","I Cover the Waterfront","I Fall in Love Too Easily",
  "Impressions","Invitation","It Had to Be You","It Never Entered My Mind",
  "Lament","Lonely Woman","Lotus Blossom","Love for Sale","Mack the Knife",
  "Manhã de Carnaval","Mean to Me","Meditation","Milestones","Misterioso",
  "Moanin'","Mood Indigo","Moose the Mooche","My Heart Stood Still","My Old Flame",
  "My One and Only Love","Nuages","Oh Lady Be Good","Once I Loved","One Note Samba",
  "Out of Nowhere","Peace","Perdido","Polka Dots and Moonbeams","Prelude to a Kiss",
  "Rhythm-a-ning","Ruby My Dear","Song for My Father","Sophisticated Lady",
  "Stompin' at the Savoy","Sweet Georgia Brown","Tea for Two","Tenderly"
];
