// jazz_data.js — Song library and practice priority order
// Edit this file to add, remove, or re-prioritize songs.
// Format: [title, style, composer, year]

const ALL_SONGS = [
  ["Stella by Starlight","","Victor Young",1944],
  ["Spring Is Here","","Richard Rodgers",1938],
  ["Rhythm-a-ning","","Thelonious Monk",1957],
  ["Limehouse Blues","","Philip Braham",1921],
  ["Nature Boy","","Eden Ahbez",1947],
  ["I Should Care","","Axel Stordahl",1944],
  ["Good Morning Heartache","","Irene Higginbotham",1945],
  ["Body and Soul","","Johnny Green",1930],
  ["I've Found a New Baby","","Jack Palmer",1926],
  ["Willow Weep for Me","","Ann Ronell",1932],
  ["Falling in Love with Love","","Richard Rodgers",1938],
  ["Lover Man","","Jimmy Davis",1941],
  ["Out of Nowhere","","Johnny Green",1931],
  ["On the Sunny Side of the Street","Trad","Jimmy McHugh",1930],
  ["Con Alma","","Dizzy Gillespie",1954],
  ["Stolen Moments","","Oliver Nelson",1961],
  ["On a Clear Day","","Burton Lane",1965],
  ["Perdido","","Juan Tizol",1941],
  ["Night Train","","Jimmy Forrest",1951],
  ["Take the A Train","","Billy Strayhorn",1941],
  ["Steeplechase","Bop","Charlie Parker",1945],
  ["Evidence","","Thelonious Monk",1948],
  ["Well You Needn't","Bop","Thelonious Monk",1944],
  ["Giant Steps","","John Coltrane",1960],
  ["How Long Has This Been Going On?","","George Gershwin",1927],
  ["Blue in Green","Modal","Miles Davis",1959],
  ["St. Thomas","","Sonny Rollins",1956],
  ["Embraceable You","","George Gershwin",1930],
  ["The Girl from Ipanema","Bossa","Antônio Carlos Jobim",1962],
  ["I Hear a Rhapsody","","George Fragos",1940],
  ["But Not for Me","","George Gershwin",1930],
  ["After You've Gone","Trad","Turner Layton",1918],
  ["It Don't Mean a Thing","Trad","Duke Ellington",1931],
  ["When the Saints Go Marching In","","Traditional",1896],
  ["Night in Tunisia","Bop","Dizzy Gillespie",1942],
  ["Bags' Groove","Blues","Milt Jackson",1952],
  ["Easy Living","","Ralph Rainger",1937],
  ["My Old Flame","","Arthur Johnston",1934],
  ["But Beautiful","","Jimmy Van Heusen",1947],
  ["Watermelon Man","","Herbie Hancock",1962],
  ["Gee Baby Ain't I Good to You","","Don Redman",1929],
  ["Don't Blame Me","","Jimmy McHugh",1932],
  ["I Fall in Love Too Easily","","Jule Styne",1944],
  ["Ornithology","Bop","Charlie Parker",1946],
  ["You Stepped Out of a Dream","","Nacio Herb Brown",1940],
  ["How Deep Is the Ocean?","","Irving Berlin",1932],
  ["Mean to Me","","Fred E. Ahlert",1929],
  ["Fascinating Rhythm","","George Gershwin",1924],
  ["Poinciana","","Nat Simon",1936],
  ["Autumn in New York","","Vernon Duke",1934],
  ["Do You Know What It Means","Trad","Louis Alter",1947],
  ["All of Me","","Gerald Marks",1931],
  ["Memories of You","","Eubie Blake",1930],
  ["I Let a Song Go Out of My Heart","","Duke Ellington",1938],
  ["C Jam Blues","Blues","Duke Ellington",1942],
  ["Speak Low","","Kurt Weill",1943],
  ["Stompin' at the Savoy","Trad","Benny Goodman",1934],
  ["It Had to Be You","","Isham Jones",1924],
  ["Bye Bye Blackbird","","Ray Henderson",1926],
  ["In a Sentimental Mood","","Duke Ellington",1935],
  ["Satin Doll","Trad","Duke Ellington",1953],
  ["Song for My Father","","Horace Silver",1964],
  ["The Nearness of You","","Hoagy Carmichael",1937],
  ["Some of These Days","","Shelton Brooks",1910],
  ["Peace","","Horace Silver",1959],
  ["I Mean You","","Thelonious Monk",1947],
  ["Maiden Voyage","Modal","Herbie Hancock",1965],
  ["Smile","","Charlie Chaplin",1936],
  ["How Insensitive","Bossa","Antônio Carlos Jobim",1963],
  ["A Child Is Born","","Thad Jones",1969],
  ["Like Someone in Love","","Jimmy Van Heusen",1944],
  ["Night and Day","","Cole Porter",1932],
  ["I Cover the Waterfront","","Johnny Green",1933],
  ["Blue Skies","Trad","Irving Berlin",1926],
  ["Ghost of a Chance","","Victor Young",1932],
  ["Anthropology","Bop","Charlie Parker",1946],
  ["East of the Sun","","Brooks Bowman",1934],
  ["The Jitterbug Waltz","","Fats Waller",1942],
  ["Lover Come Back to Me","","Sigmund Romberg",1928],
  ["My One and Only Love","","Guy Wood",1952],
  ["Dinah","Trad","Harry Akst",1925],
  ["Eternal Triangle","Bop","Sonny Stitt",1957],
  ["Don't Get Around Much Anymore","","Duke Ellington",1942],
  ["Misterioso","","Thelonious Monk",1948],
  ["Old Folks","","Willard Robison",1938],
  ["Alone Together","","Arthur Schwartz",1932],
  ["Impressions","Modal","John Coltrane",1961],
  ["Solitude","","Duke Ellington",1934],
  ["Round Midnight","","Thelonious Monk",1944],
  ["Mood Indigo","","Duke Ellington",1930],
  ["Fly Me to the Moon","","Bart Howard",1954],
  ["Now's the Time","Bop","Charlie Parker",1945],
  ["Exactly Like You","","Jimmy McHugh",1930],
  ["Honeysuckle Rose","Trad","Fats Waller",1929],
  ["Blue Moon","","Richard Rodgers",1934],
  ["Blues for Alice","Bop","Charlie Parker",1951],
  ["Mack the Knife","Trad","Kurt Weill",1928],
  ["Invitation","","Bronisław Kaper",1952],
  ["Cantaloupe Island","","Herbie Hancock",1964],
  ["Come Sunday","","Duke Ellington",1943],
  ["In a Mellow Tone","","Duke Ellington",1940],
  ["Ain't Misbehavin'","Trad","Fats Waller",1929],
  ["More Than You Know","","Vincent Youmans",1929],
  ["These Foolish Things","","Jack Strachey",1936],
  ["Donna Lee","Bop","Charlie Parker",1947],
  ["Alfie","","Burt Bacharach",1966],
  ["All Blues","","Miles Davis",1959],
  ["Moanin'","","Bobby Timmons",1958],
  ["Star Dust","","Hoagy Carmichael",1927],
  ["Nice Work If You Can Get It","","George Gershwin",1937],
  ["Spring Can Really Hang You Up the Most","","Tommy Wolf",1955],
  ["Wave","Bossa","Antônio Carlos Jobim",1967],
  ["Everything Happens to Me","","Matt Dennis",1940],
  ["I Got It Bad","","Duke Ellington",1941],
  ["Oleo","Bop","Sonny Rollins",1954],
  ["Beale Street Blues","","W.C. Handy",1916],
  ["Milestones","","Miles Davis",1958],
  ["It's Easy to Remember","","Richard Rodgers",1934],
  ["Joy Spring","Bop","Clifford Brown",1954],
  ["Liza","","George Gershwin",1929],
  ["A Foggy Day","","George Gershwin",1937],
  ["Yardbird Suite","Bop","Charlie Parker",1946],
  ["Groovin' High","Bop","Dizzy Gillespie",1945],
  ["Sophisticated Lady","","Duke Ellington",1932],
  ["I Didn't Know What Time It Was","","Richard Rodgers",1939],
  ["Oh Lady Be Good","","George Gershwin",1924],
  ["Lester Leaps In","Bop","Lester Young",1939],
  ["Things Ain't What They Used to Be","","Mercer Ellington",1941],
  ["Georgia on My Mind","","Hoagy Carmichael",1930],
  ["Tin Roof Blues","","New Orleans Rhythm Kings",1923],
  ["I Remember Clifford","","Benny Golson",1957],
  ["Whisper Not","","Benny Golson",1956],
  ["Bemsha Swing","","Thelonious Monk",1952],
  ["Ruby My Dear","","Thelonious Monk",1947],
  ["How High the Moon","","Morgan Lewis",1940],
  ["My Romance","","Richard Rodgers",1935],
  ["Tenderly","","Walter Gross",1946],
  ["Dolphin Dance","","Herbie Hancock",1965],
  ["Airegin","","Sonny Rollins",1954],
  ["You Go to My Head","","J. Fred Coots",1938],
  ["St. James Infirmary Blues","Trad","Traditional",1928],
  ["It Never Entered My Mind","","Richard Rodgers",1940],
  ["Pennies from Heaven","Trad","Arthur Johnston",1936],
  ["Tiger Rag","","ODJB",1917],
  ["Misty","","Erroll Garner",1954],
  ["Meditation","Bossa","Antônio Carlos Jobim",1962],
  ["Love for Sale","","Cole Porter",1930],
  ["I Thought about You","","Jimmy Van Heusen",1939],
  ["Sweet Georgia Brown","","Ben Bernie",1925],
  ["Darn That Dream","","Jimmy Van Heusen",1939],
  ["In Your Own Sweet Way","","Dave Brubeck",1954],
  ["Goodbye Pork Pie Hat","","Charles Mingus",1959],
  ["Lush Life","","Billy Strayhorn",1949],
  ["Chelsea Bridge","","Billy Strayhorn",1941],
  ["The Very Thought of You","","Ray Noble",1934],
  ["Love Is Here to Stay","","George Gershwin",1938],
  ["My Funny Valentine","Trad","Richard Rodgers",1937],
  ["The Lady Is a Tramp","","Richard Rodgers",1937],
  ["Confirmation","Bop","Charlie Parker",1945],
  ["Lotus Blossom","","Billy Strayhorn",1946],
  ["The Peacocks","","Jimmy Rowles",1975],
  ["Blue Bossa","Bossa","Kenny Dorham",1963],
  ["All the Things You Are","","Jerome Kern",1939],
  ["Django","Trad","John Lewis",1954],
  ["Secret Love","","Sammy Fain",1953],
  ["My Heart Stood Still","","Richard Rodgers",1927],
  ["Birdland","","Joe Zawinul",1977],
  ["Waltz for Debby","","Bill Evans",1955],
  ["My Foolish Heart","","Victor Young",1949],
  ["Star Eyes","","Gene de Paul",1943],
  ["Someone to Watch over Me","","George Gershwin",1926],
  ["Days of Wine and Roses","","Henry Mancini",1962],
  ["One O'Clock Jump","Blues","Count Basie",1937],
  ["Soul Eyes","","Mal Waldron",1957],
  ["Over the Rainbow","","Harold Arlen",1939],
  ["Moment's Notice","","John Coltrane",1957],
  ["Straight No Chaser","Blues","Thelonious Monk",1951],
  ["Tea for Two","","Vincent Youmans",1924],
  ["Along Came Betty","","Benny Golson",1958],
  ["Blue Monk","Blues","Thelonious Monk",1954],
  ["Nardis","","Miles Davis",1958],
  ["St. Louis Blues","Blues","W.C. Handy",1914],
  ["Here's That Rainy Day","","Jimmy Van Heusen",1953],
  ["April in Paris","","Vernon Duke",1932],
  ["So What","Modal","Miles Davis",1959],
  ["Easy to Love","","Cole Porter",1936],
  ["Just One of Those Things","","Cole Porter",1935],
  ["There Is No Greater Love","","Isham Jones",1936],
  ["One Note Samba","","Antônio Carlos Jobim",1960],
  ["King Porter Stomp","","Jelly Roll Morton",1906],
  ["Hot House","Bop","Tadd Dameron",1945],
  ["Angel Eyes","","Matt Dennis",1946],
  ["Bluesette","","Toots Thielemans",1962],
  ["I Got Rhythm","Trad","George Gershwin",1930],
  ["I Can't Give You Anything but Love","","Jimmy McHugh",1928],
  ["Blues in the Night","","Harold Arlen",1941],
  ["Caravan","Bop","Juan Tizol",1937],
  ["What's New?","","Bob Haggart",1939],
  ["I Love You","","Cole Porter",1943],
  ["Do Nothin' Till You Hear from Me","","Duke Ellington",1943],
  ["Lover","","Richard Rodgers",1932],
  ["All of You","","Cole Porter",1954],
  ["Nuages","","Django Reinhardt",1940],
  ["Almost Like Being in Love","","Frederick Loewe",1947],
  ["You Don't Know What Love Is","","Gene de Paul",1941],
  ["Footprints","Modal","Wayne Shorter",1966],
  ["Lullaby of Birdland","","George Shearing",1952],
  ["I Can't Get Started","","Vernon Duke",1935],
  ["Someday My Prince Will Come","","Frank Churchill",1937],
  ["S Wonderful","","George Gershwin",1927],
  ["Softly as in a Morning Sunrise","","Sigmund Romberg",1928],
  ["I'll Remember April","","Gene de Paul",1941],
  ["I'm in the Mood for Love","","Jimmy McHugh",1935],
  ["Lady Bird","","Tadd Dameron",1947],
  ["Smoke Gets in Your Eyes","","Jerome Kern",1933],
  ["Ev'ry Time We Say Goodbye","","Cole Porter",1944],
  ["If You Could See Me Now","","Tadd Dameron",1946],
  ["Corcovado","","Antônio Carlos Jobim",1960],
  ["Stormy Weather","","Harold Arlen",1933],
  ["Polka Dots and Moonbeams","","Jimmy Van Heusen",1940],
  ["Have You Met Miss Jones?","","Richard Rodgers",1937],
  ["Cherokee","Bop","Ray Noble",1938],
  ["Once I Loved","","Antônio Carlos Jobim",1965],
  ["Emily","","Johnny Mandel",1964],
  ["Solar","","Miles Davis",1954],
  ["Manhã de Carnaval","","Luiz Bonfá",1959],
  ["The Shadow of Your Smile","","Johnny Mandel",1965],
  ["God Bless the Child","","Billie Holiday",1941],
  ["Gone with the Wind","","Allie Wrubel",1937],
  ["If I Should Lose You","","Ralph Rainger",1935],
  ["On Green Dolphin Street","","Bronisław Kaper",1947],
  ["Desafinado","","Antônio Carlos Jobim",1958],
  ["Prelude to a Kiss","","Duke Ellington",1938],
  ["There Will Never Be Another You","","Harry Warren",1942],
  ["I Want to Be Happy","","Vincent Youmans",1924],
  ["The Way You Look Tonight","","Jerome Kern",1936],
  ["It Could Happen to You","","Jimmy Van Heusen",1944],
  ["The Man I Love","","George Gershwin",1924],
  ["Take Five","","Paul Desmond",1959],
  ["A Sleepin Bee","","Harold Arlen",1954],
  ["Yesterdays","","Jerome Kern",1933],
  ["They Can't Take That Away from Me","","George Gershwin",1937],
  ["What Is This Thing Called Love?","","Cole Porter",1929],
  ["Struttin' with Some Barbecue","","Lil Hardin Armstrong",1927],
  ["Autumn Leaves","","Joseph Kosma",1945],
  ["Muskrat Ramble","","Kid Ory",1926],
  ["Naima","","John Coltrane",1959],
  ["Royal Garden Blues","","Spencer Williams",1919],
  ["Lament","","J.J. Johnson",1955],
  ["Time after Time","","Jule Styne",1947],
  ["Basin Street Blues","Blues","Spencer Williams",1926],
  ["Just You Just Me","","Jesse Greer",1929],
  ["Lonely Woman","","Ornette Coleman",1960],
  ["Who Can I Turn To?","","Anthony Newley",1964],
  ["It Might as Well Be Spring","","Richard Rodgers",1945],
  ["Moose the Mooche","Bop","Charlie Parker",1946],
  ["Skylark","","Hoagy Carmichael",1941],
  ["Just Friends","","John Klenner",1931],
  ["Summertime","Trad","George Gershwin",1935],
  ["Laura","","David Raksin",1945],
  ["The Song Is You","","Jerome Kern",1932],
  ["I Surrender Dear","","Harry Barris",1931],
  ["My Favorite Things","","Richard Rodgers",1959],
  ["Billie's Bounce","Bop","Charlie Parker",1945],
  ["Scrapple from the Apple","Bop","Charlie Parker",1947],
  ["Epistrophy","","Thelonious Monk",1942],
  ["I Only Have Eyes for You","","Harry Warren",1934],
  ["Cotton Tail","","Duke Ellington",1940],
  ["Moonlight in Vermont","","Karl Suessdorf",1944],
  ["You'd Be So Nice to Come Home To","","Cole Porter",1942],
  ["Come Rain or Come Shine","","Harold Arlen",1946],
  ["Indiana","","James F. Hanley",1917],
];

// Songs ordered by jam-session priority — learned first.
// Level 1 songs appear at the top (fastest ROI), then high-frequency level 0 standards.
const PRIORITY_ORDER = [
  "Anthropology","Blues for Alice","Fly Me to the Moon","Footprints","I Got Rhythm",
  "Misty","My Funny Valentine","Ornithology","Over the Rainbow","Satin Doll",
  "Scrapple from the Apple","Soul Eyes","St. Thomas","Summertime",
  "There Will Never Be Another You","Well You Needn't","Autumn in New York",
  "Body and Soul","Come Rain or Come Shine","Days of Wine and Roses",
  "Have You Met Miss Jones?","How High the Moon","In a Sentimental Mood",
  "It Could Happen to You","Just One of Those Things","Laura","Maiden Voyage",
  "Night in Tunisia","Now's the Time","Round Midnight","Solar",
  "The Girl from Ipanema","Waltz for Debby","Watermelon Man",
  "What Is This Thing Called Love?","Yesterdays","Cherokee","Confirmation",
  "Dolphin Dance","Embraceable You","Giant Steps","Joy Spring","Lush Life",
  "Moment's Notice","Stolen Moments","Bye Bye Blackbird","Caravan",
  "Georgia on My Mind","Here's That Rainy Day","How Deep Is the Ocean?",
  "I Can't Get Started","Like Someone in Love","Lover Man","Nature Boy",
  "Naima","Speak Low","Angel Eyes","But Beautiful","Ghost of a Chance",
  "I Only Have Eyes for You","In Your Own Sweet Way","Moonlight in Vermont",
  "I Remember Clifford","Skylark","Emily","Everything Happens to Me",
  "Darn That Dream","East of the Sun","Airegin","Bemsha Swing","Bluesette",
  "Chelsea Bridge","Con Alma","Cotton Tail","Desafinado","Epistrophy",
  "Eternal Triangle","Evidence","Goodbye Pork Pie Hat","Groovin' High",
  "Hot House","How Insensitive","I Cover the Waterfront","I Fall in Love Too Easily",
  "Impressions","Invitation","It Had to Be You","It Never Entered My Mind",
  "Lament","Lonely Woman","Lotus Blossom","Love for Sale","Mack the Knife",
  "Manhã de Carnaval","Mean to Me","Meditation","Milestones","Misterioso",
  "Moanin'","Mood Indigo","Moose the Mooche","My Heart Stood Still","My Old Flame",
  "My One and Only Love","Nuages","Oh Lady Be Good","Once I Loved","One Note Samba",
  "Out of Nowhere","Peace","Perdido","Polka Dots and Moonbeams","Prelude to a Kiss",
  "Rhythm-a-ning","Ruby My Dear","Song for My Father","Sophisticated Lady",
  "Stompin' at the Savoy","Sweet Georgia Brown","Tea for Two","Tenderly"
];
