// jazz_data.js — Song library and practice priority order
// Edit this file to add, remove, or re-prioritize songs.
// Format: [title, tags, composer, year, standardKey]
// standardKey: key-center id ("Bb", "Ebm", …) or null

const ALL_SONGS = [
  ["Stella by Starlight",["Songbook","Jam"],"Victor Young",1944,"Bb"],
  ["Spring Is Here",["Ballad"],"Richard Rodgers",1938,"Ab"],
  ["Rhythm-a-ning",["Bop","Monk","Rhythm changes","Jam"],"Thelonious Monk",1957,"Bb"],
  ["Limehouse Blues",["Trad"],"Philip Braham",1921,"Ab"],
  ["Nature Boy",["Songbook","Minor"],"Eden Ahbez",1947,"Dm"],
  ["I Should Care",["Ballad"],"Axel Stordahl",1944,"C"],
  ["Good Morning Heartache",["Ballad"],"Irene Higginbotham",1945,"Cm"],
  ["Body and Soul",["Ballad","Jam"],"Johnny Green",1930,"Db"],
  ["I've Found a New Baby",["Trad","Minor"],"Jack Palmer",1926,"Eb"],
  ["Willow Weep for Me",["Ballad"],"Ann Ronell",1932,"G"],
  ["Falling in Love with Love",["Songbook"],"Richard Rodgers",1938,"Bb"],
  ["Lover Man",["Ballad"],"Jimmy Davis",1941,"F"],
  ["Out of Nowhere",["Songbook","Jam"],"Johnny Green",1931,"G"],
  ["On the Sunny Side of the Street",["Swing"],"Jimmy McHugh",1930,"C"],
  ["Con Alma",["Bop","Latin"],"Dizzy Gillespie",1954,"E"],
  ["Stolen Moments",["Hard bop","Minor"],"Oliver Nelson",1961,"Cm"],
  ["On a Clear Day",["Songbook"],"Burton Lane",1965,"G"],
  ["Perdido",["Swing","Jam"],"Juan Tizol",1941,"Bb"],
  ["Night Train",["Swing","Blues"],"Jimmy Forrest",1951,null],
  ["Take the A Train",["Swing","Jam"],"Billy Strayhorn",1941,"C"],
  ["Steeplechase",["Bop","Rhythm changes"],"Charlie Parker",1945,"Bb"],
  ["Evidence",["Bop","Monk","Contrafact"],"Thelonious Monk",1948,"Eb"],
  ["Well You Needn't",["Bop","Monk"],"Thelonious Monk",1944,"F"],
  ["Giant Steps",["Post-bop"],"John Coltrane",1960,"Eb"],
  ["How Long Has This Been Going On?",["Ballad"],"George Gershwin",1927,"F"],
  ["Blue in Green",["Modal","Ballad"],"Miles Davis",1959,"Dm"],
  ["St. Thomas",["Hard bop","Latin","Jam"],"Sonny Rollins",1956,"C"],
  ["Embraceable You",["Ballad"],"George Gershwin",1930,"G"],
  ["The Girl from Ipanema",["Bossa"],"Antônio Carlos Jobim",1962,"F"],
  ["I Hear a Rhapsody",["Songbook","Minor"],"George Fragos",1940,"Eb"],
  ["But Not for Me",["Songbook"],"George Gershwin",1930,"Eb"],
  ["After You've Gone",["Trad"],"Turner Layton",1918,"Bb"],
  ["It Don't Mean a Thing",["Swing","Minor"],"Duke Ellington",1931,"Bb"],
  ["When the Saints Go Marching In",["Trad"],"Traditional",1896,"F"],
  ["Night in Tunisia",["Bop","Latin","Minor","Jam"],"Dizzy Gillespie",1942,"Dm"],
  ["Bags' Groove",["Bop","Blues","Jam"],"Milt Jackson",1952,"F"],
  ["Easy Living",["Ballad"],"Ralph Rainger",1937,"F"],
  ["My Old Flame",["Ballad"],"Arthur Johnston",1934,"F"],
  ["But Beautiful",["Ballad"],"Jimmy Van Heusen",1947,"G"],
  ["Watermelon Man",["Hard bop","Jam"],"Herbie Hancock",1962,"F"],
  ["Gee Baby Ain't I Good to You",["Swing"],"Don Redman",1929,"Eb"],
  ["Don't Blame Me",["Ballad"],"Jimmy McHugh",1932,"C"],
  ["I Fall in Love Too Easily",["Ballad"],"Jule Styne",1944,"Eb"],
  ["Ornithology",["Bop","Contrafact"],"Charlie Parker",1946,"G"],
  ["You Stepped Out of a Dream",["Songbook"],"Nacio Herb Brown",1940,"C"],
  ["How Deep Is the Ocean?",["Songbook","Minor"],"Irving Berlin",1932,"Eb"],
  ["Mean to Me",["Songbook"],"Fred E. Ahlert",1929,"F"],
  ["Fascinating Rhythm",["Songbook"],"George Gershwin",1924,"F"],
  ["Poinciana",["Songbook","Latin"],"Nat Simon",1936,"D"],
  ["Autumn in New York",["Ballad"],"Vernon Duke",1934,"F"],
  ["Do You Know What It Means",["Trad"],"Louis Alter",1947,"C"],
  ["All of Me",["Songbook"],"Gerald Marks",1931,"C"],
  ["Memories of You",["Ballad"],"Eubie Blake",1930,"Eb"],
  ["I Let a Song Go Out of My Heart",["Swing"],"Duke Ellington",1938,"Eb"],
  ["C Jam Blues",["Swing","Blues","Jam"],"Duke Ellington",1942,"C"],
  ["Speak Low",["Songbook","Latin"],"Kurt Weill",1943,"F"],
  ["Stompin' at the Savoy",["Swing"],"Benny Goodman",1934,"Db"],
  ["It Had to Be You",["Songbook"],"Isham Jones",1924,"G"],
  ["Bye Bye Blackbird",["Songbook","Jam"],"Ray Henderson",1926,"F"],
  ["In a Sentimental Mood",["Ballad","Minor","Jam"],"Duke Ellington",1935,"Dm"],
  ["Satin Doll",["Swing","Jam"],"Duke Ellington",1953,"C"],
  ["Song for My Father",["Hard bop","Latin","Minor","Jam"],"Horace Silver",1964,"Fm"],
  ["The Nearness of You",["Ballad"],"Hoagy Carmichael",1937,"F"],
  ["Some of These Days",["Trad"],"Shelton Brooks",1910,null],
  ["Peace",["Post-bop","Ballad"],"Horace Silver",1959,"Bb"],
  ["I Mean You",["Bop","Monk"],"Thelonious Monk",1947,"F"],
  ["Maiden Voyage",["Modal","Jam"],"Herbie Hancock",1965,"D"],
  ["Smile",["Ballad"],"Charlie Chaplin",1936,"F"],
  ["How Insensitive",["Bossa","Minor"],"Antônio Carlos Jobim",1963,"Dm"],
  ["A Child Is Born",["Ballad","Waltz"],"Thad Jones",1969,"Bb"],
  ["Like Someone in Love",["Songbook"],"Jimmy Van Heusen",1944,"Eb"],
  ["Night and Day",["Songbook","Latin"],"Cole Porter",1932,"C"],
  ["I Cover the Waterfront",["Ballad"],"Johnny Green",1933,"G"],
  ["Blue Skies",["Songbook"],"Irving Berlin",1926,"C"],
  ["Ghost of a Chance",["Ballad"],"Victor Young",1932,"C"],
  ["Anthropology",["Bop","Rhythm changes","Jam"],"Charlie Parker",1946,"Bb"],
  ["East of the Sun",["Songbook"],"Brooks Bowman",1934,"G"],
  ["The Jitterbug Waltz",["Swing","Waltz"],"Fats Waller",1942,"Eb"],
  ["Lover Come Back to Me",["Songbook"],"Sigmund Romberg",1928,"Eb"],
  ["My One and Only Love",["Ballad"],"Guy Wood",1952,"C"],
  ["Dinah",["Trad"],"Harry Akst",1925,"G"],
  ["Eternal Triangle",["Bop","Rhythm changes"],"Sonny Stitt",1957,"Bb"],
  ["Don't Get Around Much Anymore",["Swing"],"Duke Ellington",1942,"C"],
  ["Misterioso",["Bop","Monk","Blues"],"Thelonious Monk",1948,"Bb"],
  ["Old Folks",["Ballad"],"Willard Robison",1938,"F"],
  ["Alone Together",["Songbook","Minor","Jam"],"Arthur Schwartz",1932,"Dm"],
  ["Impressions",["Modal","Jam"],"John Coltrane",1961,"Dm"],
  ["Solitude",["Ballad"],"Duke Ellington",1934,"Eb"],
  ["Round Midnight",["Ballad","Monk","Minor","Jam"],"Thelonious Monk",1944,"Ebm"],
  ["Mood Indigo",["Ballad"],"Duke Ellington",1930,"Ab"],
  ["Fly Me to the Moon",["Songbook"],"Bart Howard",1954,"C"],
  ["Now's the Time",["Bop","Blues","Jam"],"Charlie Parker",1945,"F"],
  ["Exactly Like You",["Songbook"],"Jimmy McHugh",1930,"C"],
  ["Honeysuckle Rose",["Swing"],"Fats Waller",1929,"F"],
  ["Blue Moon",["Songbook"],"Richard Rodgers",1934,"Eb"],
  ["Blues for Alice",["Bop","Blues","Jam"],"Charlie Parker",1951,"F"],
  ["Mack the Knife",["Songbook"],"Kurt Weill",1928,"Bb"],
  ["Invitation",["Songbook","Latin","Minor","Jam"],"Bronisław Kaper",1952,"Cm"],
  ["Cantaloupe Island",["Hard bop","Modal","Jam"],"Herbie Hancock",1964,"Fm"],
  ["Come Sunday",["Ballad"],"Duke Ellington",1943,"Bb"],
  ["In a Mellow Tone",["Swing"],"Duke Ellington",1940,"Ab"],
  ["Ain't Misbehavin'",["Swing"],"Fats Waller",1929,"C"],
  ["More Than You Know",["Ballad"],"Vincent Youmans",1929,"C"],
  ["These Foolish Things",["Ballad"],"Jack Strachey",1936,"Eb"],
  ["Donna Lee",["Bop","Contrafact","Jam"],"Charlie Parker",1947,"Ab"],
  ["Alfie",["Ballad"],"Burt Bacharach",1966,"Bb"],
  ["All Blues",["Modal","Blues","Waltz","Jam"],"Miles Davis",1959,"G"],
  ["Moanin'",["Hard bop","Minor","Jam"],"Bobby Timmons",1958,"Fm"],
  ["Star Dust",["Ballad"],"Hoagy Carmichael",1927,"Db"],
  ["Nice Work If You Can Get It",["Songbook"],"George Gershwin",1937,"G"],
  ["Spring Can Really Hang You Up the Most",["Ballad"],"Tommy Wolf",1955,"C"],
  ["Wave",["Bossa"],"Antônio Carlos Jobim",1967,"D"],
  ["Everything Happens to Me",["Ballad"],"Matt Dennis",1940,"Bb"],
  ["I Got It Bad",["Ballad"],"Duke Ellington",1941,"G"],
  ["Oleo",["Bop","Rhythm changes","Jam"],"Sonny Rollins",1954,"Bb"],
  ["Beale Street Blues",["Trad","Blues"],"W.C. Handy",1916,null],
  ["Milestones",["Modal"],"Miles Davis",1958,"Gm"],
  ["It's Easy to Remember",["Ballad"],"Richard Rodgers",1934,"Eb"],
  ["Joy Spring",["Hard bop"],"Clifford Brown",1954,"F"],
  ["Liza",["Songbook"],"George Gershwin",1929,"Eb"],
  ["A Foggy Day",["Songbook"],"George Gershwin",1937,"F"],
  ["Yardbird Suite",["Bop","Jam"],"Charlie Parker",1946,"C"],
  ["Groovin' High",["Bop","Contrafact","Jam"],"Dizzy Gillespie",1945,"Eb"],
  ["Sophisticated Lady",["Ballad"],"Duke Ellington",1932,"Ab"],
  ["I Didn't Know What Time It Was",["Songbook"],"Richard Rodgers",1939,"G"],
  ["Oh Lady Be Good",["Songbook"],"George Gershwin",1924,"G"],
  ["Lester Leaps In",["Swing","Rhythm changes","Jam"],"Lester Young",1939,"Bb"],
  ["Things Ain't What They Used to Be",["Swing","Blues"],"Mercer Ellington",1941,"Db"],
  ["Georgia on My Mind",["Ballad"],"Hoagy Carmichael",1930,"F"],
  ["Tin Roof Blues",["Trad","Blues"],"New Orleans Rhythm Kings",1923,"Bb"],
  ["I Remember Clifford",["Ballad"],"Benny Golson",1957,"Eb"],
  ["Whisper Not",["Hard bop","Minor"],"Benny Golson",1956,"Cm"],
  ["Bemsha Swing",["Bop","Monk"],"Thelonious Monk",1952,"C"],
  ["Ruby My Dear",["Ballad","Monk"],"Thelonious Monk",1947,"Eb"],
  ["How High the Moon",["Songbook"],"Morgan Lewis",1940,"G"],
  ["My Romance",["Songbook"],"Richard Rodgers",1935,"C"],
  ["Tenderly",["Ballad"],"Walter Gross",1946,"Eb"],
  ["Dolphin Dance",["Post-bop"],"Herbie Hancock",1965,"Eb"],
  ["Airegin",["Hard bop","Minor"],"Sonny Rollins",1954,"Fm"],
  ["You Go to My Head",["Ballad"],"J. Fred Coots",1938,"Eb"],
  ["St. James Infirmary Blues",["Trad","Minor"],"Traditional",1928,"Fm"],
  ["It Never Entered My Mind",["Ballad"],"Richard Rodgers",1940,"F"],
  ["Pennies from Heaven",["Songbook"],"Arthur Johnston",1936,"C"],
  ["Tiger Rag",["Trad"],"ODJB",1917,null],
  ["Misty",["Ballad"],"Erroll Garner",1954,"Eb"],
  ["Meditation",["Bossa"],"Antônio Carlos Jobim",1962,"C"],
  ["Love for Sale",["Songbook","Latin"],"Cole Porter",1930,"Bbm"],
  ["I Thought about You",["Songbook"],"Jimmy Van Heusen",1939,"F"],
  ["Sweet Georgia Brown",["Trad","Jam"],"Ben Bernie",1925,"Ab"],
  ["Darn That Dream",["Ballad"],"Jimmy Van Heusen",1939,"G"],
  ["In Your Own Sweet Way",["Hard bop"],"Dave Brubeck",1954,"Eb"],
  ["Goodbye Pork Pie Hat",["Ballad","Blues"],"Charles Mingus",1959,"F"],
  ["Lush Life",["Ballad"],"Billy Strayhorn",1949,"Db"],
  ["Chelsea Bridge",["Ballad"],"Billy Strayhorn",1941,"Db"],
  ["The Very Thought of You",["Ballad"],"Ray Noble",1934,"Ab"],
  ["Love Is Here to Stay",["Songbook"],"George Gershwin",1938,"F"],
  ["My Funny Valentine",["Ballad","Minor"],"Richard Rodgers",1937,"Cm"],
  ["The Lady Is a Tramp",["Songbook"],"Richard Rodgers",1937,"C"],
  ["Confirmation",["Bop","Jam"],"Charlie Parker",1945,"F"],
  ["Lotus Blossom",["Ballad"],"Billy Strayhorn",1946,null],
  ["The Peacocks",["Ballad"],"Jimmy Rowles",1975,"Bbm"],
  ["Blue Bossa",["Bossa","Minor","Jam"],"Kenny Dorham",1963,"Cm"],
  ["All the Things You Are",["Songbook","Jam"],"Jerome Kern",1939,"Ab"],
  ["Django",["Ballad","Minor"],"John Lewis",1954,"Fm"],
  ["Secret Love",["Songbook"],"Sammy Fain",1953,"Eb"],
  ["My Heart Stood Still",["Songbook"],"Richard Rodgers",1927,"F"],
  ["Birdland",["Post-bop"],"Joe Zawinul",1977,"F"],
  ["Waltz for Debby",["Post-bop","Waltz"],"Bill Evans",1955,"F"],
  ["My Foolish Heart",["Ballad"],"Victor Young",1949,"Bb"],
  ["Star Eyes",["Songbook","Latin"],"Gene de Paul",1943,"Eb"],
  ["Someone to Watch over Me",["Ballad"],"George Gershwin",1926,"Eb"],
  ["Days of Wine and Roses",["Songbook"],"Henry Mancini",1962,"F"],
  ["One O'Clock Jump",["Swing","Blues"],"Count Basie",1937,"F"],
  ["Soul Eyes",["Ballad"],"Mal Waldron",1957,"Cm"],
  ["Over the Rainbow",["Ballad"],"Harold Arlen",1939,"Eb"],
  ["Moment's Notice",["Post-bop"],"John Coltrane",1957,"Eb"],
  ["Straight No Chaser",["Bop","Monk","Blues","Jam"],"Thelonious Monk",1951,"Bb"],
  ["Tea for Two",["Songbook"],"Vincent Youmans",1924,"Ab"],
  ["Along Came Betty",["Hard bop"],"Benny Golson",1958,"Ab"],
  ["Blue Monk",["Bop","Monk","Blues","Jam"],"Thelonious Monk",1954,"Bb"],
  ["Nardis",["Modal","Minor"],"Miles Davis",1958,"Em"],
  ["St. Louis Blues",["Trad","Blues"],"W.C. Handy",1914,"G"],
  ["Here's That Rainy Day",["Ballad"],"Jimmy Van Heusen",1953,"G"],
  ["April in Paris",["Songbook"],"Vernon Duke",1932,"C"],
  ["So What",["Modal","Jam"],"Miles Davis",1959,"Dm"],
  ["Easy to Love",["Songbook"],"Cole Porter",1936,"G"],
  ["Just One of Those Things",["Songbook"],"Cole Porter",1935,"F"],
  ["There Is No Greater Love",["Songbook"],"Isham Jones",1936,"Bb"],
  ["One Note Samba",["Bossa"],"Antônio Carlos Jobim",1960,"Bb"],
  ["King Porter Stomp",["Trad"],"Jelly Roll Morton",1906,"Ab"],
  ["Hot House",["Bop","Contrafact"],"Tadd Dameron",1945,"C"],
  ["Angel Eyes",["Ballad","Minor"],"Matt Dennis",1946,"Cm"],
  ["Bluesette",["Blues","Waltz"],"Toots Thielemans",1962,"Bb"],
  ["I Got Rhythm",["Songbook","Rhythm changes"],"George Gershwin",1930,"Bb"],
  ["I Can't Give You Anything but Love",["Songbook"],"Jimmy McHugh",1928,"F"],
  ["Blues in the Night",["Songbook"],"Harold Arlen",1941,"G"],
  ["Caravan",["Swing","Latin","Minor","Jam"],"Juan Tizol",1937,"Fm"],
  ["What's New?",["Ballad"],"Bob Haggart",1939,"C"],
  ["I Love You",["Songbook"],"Cole Porter",1943,"F"],
  ["Do Nothin' Till You Hear from Me",["Swing"],"Duke Ellington",1943,null],
  ["Lover",["Songbook"],"Richard Rodgers",1932,"Eb"],
  ["All of You",["Songbook"],"Cole Porter",1954,"Eb"],
  ["Nuages",["Swing"],"Django Reinhardt",1940,"G"],
  ["Almost Like Being in Love",["Songbook"],"Frederick Loewe",1947,"Ab"],
  ["You Don't Know What Love Is",["Ballad","Minor"],"Gene de Paul",1941,"Fm"],
  ["Footprints",["Post-bop","Blues","Minor","Jam"],"Wayne Shorter",1966,"Cm"],
  ["Lullaby of Birdland",["Bop","Minor"],"George Shearing",1952,"Ab"],
  ["I Can't Get Started",["Ballad"],"Vernon Duke",1935,"C"],
  ["Someday My Prince Will Come",["Songbook","Waltz"],"Frank Churchill",1937,"Bb"],
  ["'S Wonderful",["Songbook"],"George Gershwin",1927,"Eb"],
  ["Softly as in a Morning Sunrise",["Songbook","Latin","Minor","Jam"],"Sigmund Romberg",1928,"Cm"],
  ["I'll Remember April",["Songbook","Latin","Jam"],"Gene de Paul",1941,"G"],
  ["I'm in the Mood for Love",["Songbook"],"Jimmy McHugh",1935,"C"],
  ["Lady Bird",["Bop","Jam"],"Tadd Dameron",1947,"C"],
  ["Smoke Gets in Your Eyes",["Ballad"],"Jerome Kern",1933,"Eb"],
  ["Ev'ry Time We Say Goodbye",["Ballad"],"Cole Porter",1944,"Eb"],
  ["If You Could See Me Now",["Ballad"],"Tadd Dameron",1946,"Eb"],
  ["Corcovado",["Bossa"],"Antônio Carlos Jobim",1960,"C"],
  ["Stormy Weather",["Songbook"],"Harold Arlen",1933,"G"],
  ["Polka Dots and Moonbeams",["Ballad"],"Jimmy Van Heusen",1940,"F"],
  ["Have You Met Miss Jones?",["Songbook","Jam"],"Richard Rodgers",1937,"F"],
  ["Cherokee",["Bop","Jam"],"Ray Noble",1938,"Bb"],
  ["Once I Loved",["Bossa"],"Antônio Carlos Jobim",1965,"Dm"],
  ["Emily",["Ballad","Waltz"],"Johnny Mandel",1964,"G"],
  ["Solar",["Hard bop","Minor","Jam"],"Miles Davis",1954,"Cm"],
  ["Manhã de Carnaval",["Bossa","Minor"],"Luiz Bonfá",1959,"Am"],
  ["The Shadow of Your Smile",["Songbook"],"Johnny Mandel",1965,"G"],
  ["God Bless the Child",["Songbook"],"Billie Holiday",1941,"Eb"],
  ["Gone with the Wind",["Songbook"],"Allie Wrubel",1937,"Eb"],
  ["If I Should Lose You",["Songbook"],"Ralph Rainger",1935,"Bb"],
  ["On Green Dolphin Street",["Songbook","Latin","Jam"],"Bronisław Kaper",1947,"Eb"],
  ["Desafinado",["Bossa"],"Antônio Carlos Jobim",1958,"F"],
  ["Prelude to a Kiss",["Ballad"],"Duke Ellington",1938,"C"],
  ["There Will Never Be Another You",["Songbook","Jam"],"Harry Warren",1942,"Eb"],
  ["I Want to Be Happy",["Songbook"],"Vincent Youmans",1924,"C"],
  ["The Way You Look Tonight",["Songbook"],"Jerome Kern",1936,"F"],
  ["It Could Happen to You",["Songbook"],"Jimmy Van Heusen",1944,"Eb"],
  ["The Man I Love",["Songbook"],"George Gershwin",1924,"Eb"],
  ["Take Five",["Minor","Odd meter"],"Paul Desmond",1959,"Ebm"],
  ["A Sleepin Bee",["Songbook"],"Harold Arlen",1954,"Ab"],
  ["Yesterdays",["Songbook","Minor"],"Jerome Kern",1933,"Dm"],
  ["They Can't Take That Away from Me",["Songbook"],"George Gershwin",1937,"Eb"],
  ["What Is This Thing Called Love?",["Songbook","Jam"],"Cole Porter",1929,"C"],
  ["Struttin' with Some Barbecue",["Trad"],"Lil Hardin Armstrong",1927,"F"],
  ["Autumn Leaves",["Songbook","Minor","Jam"],"Joseph Kosma",1945,"Gm"],
  ["Muskrat Ramble",["Trad"],"Kid Ory",1926,"Bb"],
  ["Naima",["Post-bop","Ballad"],"John Coltrane",1959,"Ab"],
  ["Royal Garden Blues",["Trad"],"Spencer Williams",1919,"F"],
  ["Lament",["Ballad"],"J.J. Johnson",1955,"Fm"],
  ["Time after Time",["Songbook"],"Jule Styne",1947,"C"],
  ["Basin Street Blues",["Trad"],"Spencer Williams",1926,"Bb"],
  ["Just You Just Me",["Songbook"],"Jesse Greer",1929,"C"],
  ["Lonely Woman",["Post-bop","Minor"],"Ornette Coleman",1960,"Dm"],
  ["Who Can I Turn To?",["Ballad"],"Anthony Newley",1964,"Eb"],
  ["It Might as Well Be Spring",["Songbook"],"Richard Rodgers",1945,"G"],
  ["Moose the Mooche",["Bop","Rhythm changes"],"Charlie Parker",1946,"Bb"],
  ["Skylark",["Ballad"],"Hoagy Carmichael",1941,"Eb"],
  ["Just Friends",["Songbook","Jam"],"John Klenner",1931,"G"],
  ["Summertime",["Songbook","Minor"],"George Gershwin",1935,"Am"],
  ["Laura",["Songbook"],"David Raksin",1945,"C"],
  ["The Song Is You",["Songbook"],"Jerome Kern",1932,"C"],
  ["I Surrender Dear",["Songbook"],"Harry Barris",1931,"C"],
  ["My Favorite Things",["Modal","Waltz"],"Richard Rodgers",1959,"Em"],
  ["Billie's Bounce",["Bop","Blues","Jam"],"Charlie Parker",1945,"F"],
  ["Scrapple from the Apple",["Bop","Contrafact","Jam"],"Charlie Parker",1947,"F"],
  ["Epistrophy",["Bop","Monk"],"Thelonious Monk",1942,"Db"],
  ["I Only Have Eyes for You",["Songbook"],"Harry Warren",1934,"C"],
  ["Cotton Tail",["Swing","Rhythm changes"],"Duke Ellington",1940,"Bb"],
  ["Moonlight in Vermont",["Ballad"],"Karl Suessdorf",1944,"Eb"],
  ["You'd Be So Nice to Come Home To",["Songbook","Minor"],"Cole Porter",1942,"Am"],
  ["Come Rain or Come Shine",["Songbook"],"Harold Arlen",1946,"F"],
  ["Indiana",["Trad"],"James F. Hanley",1917,"F"],
  ["Tenor Madness",["Hard bop","Blues","Jam"],"Sonny Rollins",1956,"Bb"],
  ["Mr. P.C.",["Hard bop","Blues","Minor","Jam"],"John Coltrane",1959,"Cm"],
  ["Four",["Hard bop","Jam"],"Miles Davis",1954,"Eb"],
  ["Recorda Me",["Hard bop","Latin","Minor","Jam"],"Joe Henderson",1963,"Am"],
  ["Doxy",["Hard bop","Jam"],"Sonny Rollins",1954,"Bb"]
];

// Songs ordered by jam-session priority — learned first.
// Level 1 songs appear at the top (fastest ROI), then high-frequency level 0 standards.
const PRIORITY_ORDER = [
  "Anthropology","Blues for Alice","Fly Me to the Moon","Footprints","I Got Rhythm",
  "Misty","My Funny Valentine","Ornithology","Over the Rainbow","Satin Doll",
  "Scrapple from the Apple","Soul Eyes","St. Thomas","Summertime",
  "There Will Never Be Another You","Well You Needn't","Autumn in New York",
  "Body and Soul","Come Rain or Come Shine","Days of Wine and Roses",
  "Have You Met Miss Jones?","How High the Moon","In a Sentimental Mood",
  "It Could Happen to You","Just One of Those Things","Laura","Maiden Voyage",
  "Night in Tunisia","Now's the Time","Round Midnight","Solar",
  "The Girl from Ipanema","Waltz for Debby","Watermelon Man",
  "What Is This Thing Called Love?","Yesterdays","Cherokee","Confirmation",
  "Dolphin Dance","Embraceable You","Giant Steps","Joy Spring","Lush Life",
  "Moment's Notice","Stolen Moments","Bye Bye Blackbird","Caravan",
  "Georgia on My Mind","Here's That Rainy Day","How Deep Is the Ocean?",
  "I Can't Get Started","Like Someone in Love","Lover Man","Nature Boy",
  "Naima","Speak Low","Angel Eyes","But Beautiful","Ghost of a Chance",
  "I Only Have Eyes for You","In Your Own Sweet Way","Moonlight in Vermont",
  "I Remember Clifford","Skylark","Emily","Everything Happens to Me",
  "Darn That Dream","East of the Sun","Airegin","Bemsha Swing","Bluesette",
  "Chelsea Bridge","Con Alma","Cotton Tail","Desafinado","Epistrophy",
  "Eternal Triangle","Evidence","Goodbye Pork Pie Hat","Groovin' High",
  "Hot House","How Insensitive","I Cover the Waterfront","I Fall in Love Too Easily",
  "Impressions","Invitation","It Had to Be You","It Never Entered My Mind",
  "Lament","Lonely Woman","Lotus Blossom","Love for Sale","Mack the Knife",
  "Manhã de Carnaval","Mean to Me","Meditation","Milestones","Misterioso",
  "Moanin'","Mood Indigo","Moose the Mooche","My Heart Stood Still","My Old Flame",
  "My One and Only Love","Nuages","Oh Lady Be Good","Once I Loved","One Note Samba",
  "Out of Nowhere","Peace","Perdido","Polka Dots and Moonbeams","Prelude to a Kiss",
  "Rhythm-a-ning","Ruby My Dear","Song for My Father","Sophisticated Lady",
  "Stompin' at the Savoy","Sweet Georgia Brown","Tea for Two","Tenderly"
];

// Transcription books and the tunes they contain. Titles that are in ALL_SONGS use
// the library spelling; the rest are kept as printed so a song added later picks
// its books up automatically.
const TRANSCRIPTION_BOOKS = [
  { title: "Clifford Brown Vol. 2", songs: [
    "What Is This Thing Called Love?", "I'll Remember April", "Powell's Prances",
    "Gertrude's Bounce", "Sweet Clifford", "Stompin' at the Savoy",
    "I Get a Kick Out of You", "Ghost of a Chance", "Cherokee", "Jacqui", "Swingin'",
    "Land's End", "Sandu", "If I Love Again", "Take the A Train", "Delilah",
    "Parisian Thoroughfare", "The Blues Walk", "Joy Spring", "Jordu",
    "What Am I Here For?", "Daahoud", "You Go to My Head", "Flossie Lou",
    "Step Lightly (Junior's Arrival)",
  ]},
  { title: "Bud Powell Omnibook", songs: [
    "All God's Chillun Got Rhythm", "All the Things You Are", "April in Paris",
    "Autumn in New York", "Bags' Groove", "Blues in the Closet", "Body and Soul",
    "Bouncing with Bud", "Bud's Bubble", "Celia", "Cherokee", "Elogie",
    "52nd Street Theme", "Fine and Dandy", "Get Happy", "Glass Enclosure",
    "Hallucinations", "Hot House", "I'll Remember April", "It Could Happen to You",
    "It Never Entered My Mind", "Just One of Those Things", "Night in Tunisia",
    "Oblivion", "Off Minor", "Parisian Thoroughfare", "Ruby My Dear", "Satin Doll",
    "So Sorry Please", "Stairway to the Stars", "Sweet Georgia Brown", "Tea for Two",
    "Tempus Fugit", "There Will Never Be Another You", "Un Poco Loco",
  ]},
  { title: "Charlie Parker Omnibook", songs: [
    "Ah-Leu-Cha", "Another Hairdo", "Anthropology", "Au Privave", "Back Home Blues",
    "Ballade", "Barbados", "Billie's Bounce", "The Bird", "Bird Gets the Worm",
    "Bloomdido", "Blue Bird", "Blues (Fast)", "Blues for Alice", "Buzzy", "Card Board",
    "Celerity", "Chasing the Bird", "Cheryl", "Chi Chi", "Confirmation", "Constellation",
    "Cosmic Rays", "Dewey Square", "Diverse", "Donna Lee", "K.C. Blues", "Kim",
    "Klaun Stance", "Ko Ko", "Laird Baird", "Leap Frog", "Marmaduke", "Merry-Go-Round",
    "Mohawk", "Moose the Mooche", "My Little Suede Shoes", "Now's the Time",
    "Ornithology", "An Oscar for Treadwell", "Parker's Mood", "Passport", "Perhaps",
    "Red Cross", "Relaxing with Lee", "Scrapple from the Apple", "Segment", "Shawnuff",
    "She Rote", "Si Si", "Steeplechase", "Thriving from a Riff", "Visa",
    "Warming Up a Riff", "Yardbird Suite",
  ]},
  { title: "Cannonball Adderley Omnibook", songs: [
    "Ah-Leu-Cha", "Azule Serape", "Batida Diferente", "Blue Funk", "Cannonball",
    "Country Preacher", "Del Sasser", "Easy to Love", "Fiddler on the Roof",
    "Groovy Samba", "Hi-Fly", "Hoppin' John", "Hurricane Connie", "I Remember You",
    "I'm on My Way", "Introduction to a Samba", "Jeannine", "Love for Sale", "Marabi",
    "Milestones", "Minority", "Oleo", "On Green Dolphin Street", "Once I Loved",
    "One for Daddy-O", "People Will Say We're in Love", "Poor Butterfly", "Porky",
    "Corcovado", "Rumple Stiltskin", "Sack of Woe", "Scotch and Water",
    "Seventy Four Miles Away (74 Miles Away)", "So What", "Somethin' Else", "Spectacular",
    "Spontaneous Combustion", "Star Dust", "Straight No Chaser", "The Theme (The Scene)",
    "Things Are Getting Better", "This Here", "Toy", "Unit 7", "Waltz for Debby",
    "What Is This Thing Called Love?", "Who Cares? (So Long as You Care for Me)",
    "Work Song", "You Got It",
  ]},
  { title: "Sonny Rollins Omnibook", songs: [
    "Airegin", "All the Things You Are", "Almost Like Being in Love", "Blue Seven",
    "Bouncing with Bud", "But Not for Me", "Compulsion", "Dance of the Infidels", "Dig",
    "Down", "Doxy", "Ev'ry Time We Say Goodbye", "52nd Street Theme",
    "I Know That You Know", "I Remember You", "I Want to Be Happy", "I'll Remember April",
    "I'll Take Romance", "In Your Own Sweet Way", "Just in Time",
    "The Last Time I Saw Paris", "Mambo Bounce", "Moving Out", "Namely You", "No Moe",
    "Old Devil Moon", "Oleo", "On a Slow Boat to China", "Out of the Blue",
    "Pent Up House", "Raincheck", "St. Thomas", "The Scene Is Clean", "Scoops",
    "The Serpent's Tooth", "Solid", "Sonnymoon for Two", "Strode Rode", "Tenor Madness",
    "There Will Never Be Another You", "Toot, Toot, Tootsie! (Good-Bye!)", "Tune Up",
    "Valse Hot", "Vierd Blues", "Wail", "What Is This Thing Called Love?",
    "When Your Lover Has Gone", "Whispering", "Woodyn' You", "You Stepped Out of a Dream",
  ]},
  { title: "Oscar Peterson Omnibook", songs: [
    "Alice in Wonderland", "All of Me", "Bags' Groove", "Blues Etude", "Cheek to Cheek",
    "Con Alma", "Falling in Love with Love", "Georgia on My Mind", "Girl Talk",
    "Hymn to Freedom", "I'm a Fool to Want You", "I'm Old Fashioned",
    "I've Got a Crush on You", "If I Were a Bell",
    "In the Wee Small Hours of the Morning", "It's All Right with Me", "It's De-Lovely",
    "Love for Sale", "The Man I Love", "Nica's Dream", "On Green Dolphin Street",
    "Softly as in a Morning Sunrise", "Sometimes I'm Happy", "The Song Is You",
    "Tangerine", "That Old Black Magic", "Waltz for Debby", "Wave", "Whisper Not",
    "You Stepped Out of a Dream", "Younger Than Springtime", "Yours Is My Heart Alone",
  ]},
];
